<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class UnitResource extends JsonResource
{
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'unit_uuid' => $this->unit_uuid,
            'unit_code' => $this->unit_code,
            'unit_external_id' => $this->unit_external_id,
            'project' => $this->whenLoaded('project', $this->project ? $this->project->only('id', 'name', 'project_code') : null),
            'property' => $this->whenLoaded('property', $this->property ? $this->property->only('id', 'property_code') : null),
            'property_type' => $this->whenLoaded('propertyType', $this->propertyType ? $this->propertyType->only('id', 'name') : null),
            'status' => $this->whenLoaded('status', $this->status ? $this->status->only('id', 'name') : null),
            'neighborhood' => $this->neighborhood,
            'status_reason' => $this->status_reason,
            'floor' => $this->floor,
            'area' => $this->area,
            'building_surface_area' => $this->building_surface_area,
            'housh_area' => $this->housh_area,
            'rooms' => $this->rooms,
            'wc_number' => $this->wc_number,
            'price' => $this->price,
            'price_base' => $this->price_base,
            'currency' => $this->currency,
            'exchange_rate' => $this->exchange_rate,
            'model' => $this->model,
            'purpose' => $this->purpose,
            'unit_type' => $this->unit_type,
            'owner' => $this->owner,
            'instrument_no' => $this->instrument_no,
            'instrument_hijri_date' => $this->instrument_hijri_date,
            'instrument_no_after_sales' => $this->instrument_no_after_sales,
            'unit_description_en' => $this->unit_description_en,
            'national_address' => $this->national_address,
            'water_meter_no' => $this->water_meter_no,
            'has_balcony' => $this->has_balcony,
            'has_basement' => $this->has_basement,
            'has_basement_parking' => $this->has_basement_parking,
            'has_big_housh' => $this->has_big_housh,
            'has_small_housh' => $this->has_small_housh,
            'has_housh' => $this->has_housh,
            'has_big_roof' => $this->has_big_roof,
            'has_small_roof' => $this->has_small_roof,
            'has_roof' => $this->has_roof,
            'has_rooftop' => $this->has_rooftop,
            'has_pool' => $this->has_pool,
            'has_pool_view' => $this->has_pool_view,
            'has_tennis_view' => $this->has_tennis_view,
            'has_golf_view' => $this->has_golf_view,
            'has_caffe_view' => $this->has_caffe_view,
            'has_waterfall' => $this->has_waterfall,
            'has_elevator' => $this->has_elevator,
            'has_private_entrance' => $this->has_private_entrance,
            'has_two_interfaces' => $this->has_two_interfaces,
            'has_security_system' => $this->has_security_system,
            'has_internet' => $this->has_internet,
            'has_kitchen' => $this->has_kitchen,
            'has_laundry_room' => $this->has_laundry_room,
            'has_internal_store' => $this->has_internal_store,
            'has_warehouse' => $this->has_warehouse,
            'has_living_room' => $this->has_living_room,
            'has_family_lounge' => $this->has_family_lounge,
            'has_big_lounge' => $this->has_big_lounge,
            'has_food_area' => $this->has_food_area,
            'has_council' => $this->has_council,
            'has_diwaniyah' => $this->has_diwaniyah,
            'has_diwan1' => $this->has_diwan1,
            'has_mens_council' => $this->has_mens_council,
            'has_womens_council' => $this->has_womens_council,
            'has_family_council' => $this->has_family_council,
            'has_maids_room' => $this->has_maids_room,
            'has_drivers_room' => $this->has_drivers_room,
            'has_terrace' => $this->has_terrace,
            'has_outdoor' => $this->has_outdoor,
            'deleted_at' => $this->deleted_at,
        ];
    }
}
